### ISSUE TITLE
Q: What exactly do list-inactive and list-active do?

### ISSUE THREAD

**Issue by eli-oat** [0xl3vi/hostsctl#3]
I'm not entirely certain what these commands do. 

My assumption is that `list-active` displays all connections that are being actively blocked at the moment, but I'm not sure.

**Comment by 0xl3vi** [comment]
No it will show you what hosts /etc/hosts is blocking.

* Example lines from /etc/hosts:

``` {bash}
0.0.0.0 domain.ltd #inactive domain
#0.0.0.0 domain.ltd # active domain (not pointed to 0.0.0.0)
```

hope it helps :+1:

**Comment by pigmonkey** [comment]
The active/inactive terminology is a little confusing. I had to look through the script to see which was which.

hostsctl exists to block hosts, so "active" could mean that blocking is active for the host. Or it could mean that the domain is not blocked, so that I can communicate with it. The latter is of course the meaning that hostsctl currently uses.

Swapping these to `list-enabled` and `list-disabled` may be more intuitive, and would keep things consistent with the `enable` and `disable` switches.

**Comment by 0xl3vi** [comment]
@pigmonkey yes it's a good idea to rename the functions,
can you create a pull request? to document this change by you.
