### ISSUE TITLE
hostsctl should not non-interactively clobber existing hostsfiles without warning

### ISSUE THREAD

**Issue by thomas-profitt** [0xl3vi/hostsctl#6]
After running `hostsctl update`, my old hostsfile was replaced.

hostsctl should simply append its entries to the existing hostsfile, or at least prompt the user before overwriting it. I didn't have the addresses of my hosts entries backed up anywhere, so I've lost data.

**Comment by 0xl3vi** [comment]
Hi @thomas-profitt sorry for you data lost,

this is great idea, maybe we need to create backup before calling `hosts_update`
something like `/etc/hosts.bak and then we can restore/merge the original.

do you want to create a pull request to document this change by you?

**Comment by thomas-profitt** [comment]
I agree that creating a backup is ideal regardless of how hostsctl actually alters the hostsfile.

I would back it up in /tmp/hosts.bak, and notify the user, before hostsctl does anything.

I also think hostsctl shouldn't overwrite the file contents anyway. I think it could be as simple as this:
Instead of operating on the entire hostsfile, hostsctl could operate only on a section of it, which it would separate from the rest of the file by marking the beginning and ending of the section with unique comments.

Example:
`hostsctl update` is ran for the first time. It creates an empty section at the bottom of the hostsfile, then writes its changes into the section.
`hostsctl update` is ran a second time, this time with an existing section created. It overwrites the contents of the section.

This is ideal because it doesn't depend on any kind of merge logic, it keeps hostsctl's changes contained, and it doesn't matter where in the file the section is.

I'm not good enough with bash to feel comfortable making the change myself.

(It really sucks that we don't have an /etc/hosts.d!)

**Comment by 0xl3vi** [comment]
@thomas-profitt I agree.
`hostsctl update` will not overwrite the orignal
I will make the changes soon.

thank you very much :smile:

**Comment by pigmonkey** [comment]
I think we want 3 sections:

1. The user's original entries
2. Entries that have been added via `hostctl enable` and `hostctl disable`
3. The contents of the blocking hosts file.

When `hostctl update` is run, it only overwrites section 3. This addresses @thomas-profitt's issue, and also solves the problem of losing enabled/disabled hosts on update.

> (It really sucks that we don't have an /etc/hosts.d!)

That's not a bad idea. What if we created an `/etc/hostsctl.d` that included three files by default:

1. `/etc/hostsctl.d/10-hosts.orig`: the user's original entries
2. `/etc/hostsctl.d/20-enabled-disabled`: entries added through `hostctl enable` and `hostctl disable`
3. `/etc/hostsctl.d/30-remote`: the blocking file that we download

`hostsctl update` overwrites `/etc/hostsctl.d/30-remote`. `hostctl enable` and `hostctl disable` modify `/etc/hostsctl.d/20-enabled-disabled`. After either of those three commands, hostctl just does a `cat /etc/hostctl.d/* >! /etc/hosts`. That may be simpler than trying to modify the file in place and juggling the three sections. Instead of outputting directly to `/etc/hosts`, we could also pipe into some sort of de-duper to address #4.

We would have to make sure that the users knows that any changes they make to `/etc/hosts` will be blown away and that they should instead make any customizations in `/etc/hostsctl.d/10-hosts.orig` (or any other file in that directory).

**Comment by 0xl3vi** [comment]
@pigmonkey I will start working on this,

Changes
-------------
* /etc/hostsctl.d/* will define the hosts.
* `enable/disable` commands will write to `/etc/hostsctl.d/20-enabled-disabled`

or `/etc/hostsctl.d/20-enabled` -  `/etc/hostsctl.d/30-disabled`

* `update` command will update /etc/hostsctl.d/30-remote.

and then we wil merge /etc/hostsctl.d/* to /etc/hosts.
I will also create AUR package.

**Comment by m1guelpf** [comment]
@0xl3vi Remember to also merge /etc/hostsctl.d/* to /etc/hosts when running enable/disable!

**Comment by 0xl3vi** [comment]
@m1guelpf @pigmonkey what if we will add config file something like:

`/etc/hostsctl.d/config:`
```{bash
remote_hosts = http://server/hosts.txt
local_hosts     = /etc/hosts
```

**Comment by pigmonkey** [comment]
A config file to define the remote hosts is useful. I would put it at `/etc/hostctl.conf` or something like that so that we can assume every file in `/etc/hostsctl.d/` is an entry to be merged.

What is the `local_hosts` var for?

**Comment by pigmonkey** [comment]
Do you mean that the user would keep custom entries in `/home/user/.hosts` that would be merged in to hostctl's output to `/etc/hosts`? Or that hostctl would output its merged files to `/home/user/.hosts`?

If the former, I think it's simpler to just have the user dump their custom entries into a file in `/etc/hostctl.d`.

If the latter, I can't think of a reason why I would want to output the merged files anyplace other than `/etc/hosts`, but I supposed there's no reason not to give the user the option to easily do that. Although a slightly more unix-y approach may be to provide `hostctl merge` that just outputs to stdout, so that the user can `hostctl merge > ~/.hosts` if they want to. In that case `hostctl update` basically just calls `hostctl merge >! /etc/hosts` internally.

I actually like that idea, because now I can diff changes fairly easily. Say there is an option to update `/etc/hostctl.d/30-remote` without actually merging (`hostctl update-only` or something). Now I can use `hostctl merge` to compare the new files against my current `/etc/hosts`

    $ hostctl merge | diff /etc/hosts -

If I'm happy with the changes, then I can "save" them with `hostsctl merge >! /etc/hosts`. Or maybe there is a `hostctl save` or something that does that for me. (I wouldn't want to run `hostctl update` to save the changes because that would download the remote file again and there may have been changes since I diffed -- but if I didn't care to diff first, `hostctl update` would basically be the equivalent of `hostctl update-only && hostctl save`).

I was happy with hostctl when I found it yesterday, but I'm excited for where this is going. :smile:

**Comment by 0xl3vi** [comment]
OK we have initial version.

Whats new
-----------------

#### Commands
* export: export /etc/hostsctl.d/* to stdout.
* remote-update : update the remote hosts file.
* merge : merge /etc/hostsctl.d/* to /etc/hosts.

All the changes we talked about were implemented.

@pigmonkey can you please write the new README? (you will explain better than me how hostsctl works :smile: )

I also created `install.sh` script to simplify the installation

the original `hostsctl.sh` is kept in a new branch `original` it's useful script, 
and some people prefer to use the old script.
this is alpha version, we need more tests etc..

that's it!

**Comment by pigmonkey** [comment]
Sure. I'll look through the changes and take a shot at the docs in the
next couple days.

**Comment by 0xl3vi** [comment]
I think we can close this? @thomas-profitt @pigmonkey

**Comment by thomas-profitt** [comment]
Yes. I think the solution is very sensible :D
